# Generated by Django 5.0.4 on 2024-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0003_reply_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
